# APP
app.workspace.default-quota=1073741824
app.storage.max-file-size=10485760

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

# SQL
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate

# JWT
jwt.secret=aab26daecc7ca1b694a2744f498e28ac08ba2d9c89191124c54af63e2307f8a6
jwt.issuer=SYSTEM
jwt.expiration=1800

refresh.token.expiration=604800

aws.s3.bucket=${AWS_BUCKET}
aws.region=${AWS_REGION}